// Add icon name to this file and run the generator to create the icons.json file
export const allowedIconNames = [
  'house',
  'chevron-down',
  'trash',
  'xmark',
  'filter',
  'magnifying-glass',
  'arrow-right',
  'arrows-rotate',
  'check',
  'circle-check',
  'triangle-exclamation',
  'circle-xmark',
  'pen',
  'bag-shopping',
  'life-ring',
  'bolt',
  'calendar-clock',
  'keyboard',
  'file-signature',
  'envelope-open-text',
  'gear',
  'file-invoice-dollar',
  'building',
  'user',
  'calendar',
  'copy',
  'eye',
  'phone',
  'paper-plane',
  'download',
  'paperclip',
  'file-user',
  'plus',
  'graduation-cap',
  'wallet',
  'location-dot',
  'circle-info',
  'cloud-arrow-up',
  'triangle-exclamation',
  'image',
  'file-lines',
  'clock',
  'pen-to-square',
  'pen-nib',
  'trash-can',
  'lock',
  'arrow-right-from-bracket',
  'briefcase'
] as const;

export type IconName = (typeof allowedIconNames)[number];
